### ISSUE TITLE
When quote is closed show the last 4 lines instead of the first 4 lines.

### ISSUE THREAD

**Issue by school-bus-driver** [IMC-GER/phpBB-Collapse-Quote#1]
Hello, Thanks for this great extension.

i would like to suggest a issue that makes it a little uncomfortable

in acp i set that it should only show 4 lines when i close the quote, the 4 lines that i see are from the older quotes. 
rather the 4 lines should show the last quote and up.

is it possible to change?

Thank you

**Comment by school-bus-driver** [comment]
And is it possible to add a option ucp that every user should have the option to enable/disable this feature?

Thanks again

**Comment by IMC-GER** [comment]
Hi, sorry for the late answer.

An option in the ucp to enable/disable CollapsQuotes is an good idee. I will add it in the next update.

To show the last 4 lines instead of the first 4 lines. Normaly i read, and many people too, a text from the top to bottom. So i read the first lines and be interested to read more or not. I will think about it a bit more if I make this also selectable as an option in the UCP.

**Comment by school-bus-driver** [comment]
> Hi, sorry for the late answer.
> 
> An option in the ucp to enable/disable CollapsQuotes is an good idee. I will add it in the next update.
> 
> To show the last 4 lines instead of the first 4 lines. Normaly i read, and many people too, a text from the top to bottom. So i read the first lines and be interested to read more or not. I will think about it a bit more if I make this also selectable as an option in the UCP.

Thank you!

How soon can we see a update?

**Comment by IMC-GER** [comment]
> How soon can we see a update?

Maybe next month.

**Comment by school-bus-driver** [comment]
> > How soon can we see a update?
> 
> Maybe next month.

Thank you vary much!

Im waiting...

**Comment by school-bus-driver** [comment]
Hello, I just installed the extension on my live board... And I have already been asked from a few members if it's possible to see the last lines instead of the first lines...

**Comment by IMC-GER** [comment]
Ok.
At time i am very busy. I try it next month.

**Comment by IMC-GER** [comment]
v1.2.0 is ready for download.

**Comment by ChaimWieder** [comment]
Thanks! 
Will test it, and get it on my board!
