### ISSUE TITLE
When it's set to show the bottom lines, it is kind of overstepping on other elements.

### ISSUE THREAD

**Issue by ChaimWieder** [IMC-GER/phpBB-Collapse-Quote#2]
when its set to show the bottom lines, it is kind of overstepping on other elements.

![image](https://github.com/IMC-GER/phpBB-Collapse-Quote/assets/113867156/524fdbb7-d92c-46a7-9111-3fedc02f2e7e)
![image](https://github.com/IMC-GER/phpBB-Collapse-Quote/assets/113867156/9321330d-b856-419c-a367-a3b24549b0a4)

**Comment by IMC-GER** [comment]
Thanks for the bug report,
V1.2.1 in ready for download.

**Comment by ChaimWieder** [comment]
Thanks! works just fine!
